declare const express: any;
declare const mongoose: any;
declare const morgan: any;
declare const cors: any;
declare const path: any;
declare const Post: any;
declare const postsRouter: any;
declare const app: any;
declare const port: string | number;
declare const DB_URL: string;
